version: 0.2

phases:
  build:
    commands:
  post_build:
    commands:
     - mkdir build
     - cp -R rasa_june_16/* build/
     - cp requirements.txt build/

artifacts:
  base-directory: build
  files:
    - '**/*'
  exclude-paths:
    - models_archive/*
